global using FluentValidation;
global using FluentValidation.TestHelper;
global using InsuranceProposal.UnitTest.Common._Builders;
global using InsuranceProposal.UnitTest.Common._Extensions;
global using InsuranceProposal.UnitTest.Common._Helpers;
global using Microsoft.Extensions.Logging;
global using NSubstitute;
global using ProposalService.Application;
global using ProposalService.Domain.Entities;
global using ProposalService.Domain.Interfaces;
global using ProposalService.Domain.Requests;
global using ProposalService.UnitTest._Builders.Entities;
global using ProposalService.UnitTest._Builders.Requests;
global using static InsuranceProposal.UnitTest.Common._Helpers.DbSetHelpers;
