// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace ContractService.Persistence.Migrations;

[DbContext(typeof(ContractContext))]
partial class ContractContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.7")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("ContractService.Domain.Entities.Contract", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("created_at");

                b.Property<Guid>("IdProposal")
                    .HasColumnType("uuid")
                    .HasColumnName("id_proposal");

                b.Property<DateTime>("SignAt")
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("sign_at");

                b.HasKey("Id")
                    .HasName("pk_contracts");

                b.ToTable("contracts", (string)null);
            });
#pragma warning restore 612, 618
    }
}
