global using InsuranceProposal.Common.Helpers;
global using InsuranceProposal.Common.Requests;
global using InsuranceProposal.Common.Responses;
global using Microsoft.Extensions.DependencyInjection;
global using ProposalService.Domain.Entities;
global using ProposalService.Domain.Interfaces;
global using ProposalService.Domain.Interfaces.Services;
global using ProposalService.Domain.Requests;
global using ProposalService.Domain.Responses;
