global using ContractService.Domain;
global using ContractService.Domain.Entities;
global using ContractService.Domain.Enums;
global using ContractService.Domain.Interfaces;
global using ContractService.Domain.Interfaces.Repositories;
global using ContractService.Domain.Interfaces.Services;
global using ContractService.Domain.Requests;
global using ContractService.Domain.Responses;
global using Microsoft.Extensions.DependencyInjection;
